name: village_council_app
description: Village Council App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.19
  flutter_local_notifications: 19.5.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: ^13.2.0
  file_picker: ^8.0.3
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^3.1.0
  percent_indicator: ^4.2.3
  timeline_tile: ^2.0.0
  pinput: ^3.0.1
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0
  uuid: ^4.4.0
  url_launcher: ^6.2.6
  app_settings: ^5.1.1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
