// Generated by setup_apps.js
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('Unsupported platform');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1pJh9ttTE7NPkaA_M3l_6jmmS0ETbpjQ',
    appId: '1:501018693703:android:cf34b84e3613940662e162',
    messagingSenderId: '501018693703',
    projectId: 'alrahmat-console',
    storageBucket: 'alrahmat-console.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi-KRa5duJtRsyKzLGdI9q6Ety3WJkk1M',
    appId: '1:501018693703:ios:a75cb2c8b4651ac162e162',
    messagingSenderId: '501018693703',
    projectId: 'alrahmat-console',
    storageBucket: 'alrahmat-console.firebasestorage.app',
    iosClientId: '',
    iosBundleId: 'com.alrahmat.villageCouncil',
  );
}
